apiVersion: v1
kind: ConfigMap
metadata:
  name: codechallenge2-cm
data:
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: {{ .Values.datasource.maximumPoolSize | quote}}
  SPRING_DATASOURCE_URL: {{ .Values.datasource.databaseUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.datasource.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.datasource.password | quote }}
  SERVER_SHUTDDOWN: graceful