apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-service
      name: http
    - port: {{ .Values.managementService.port }}
      targetPort: http-management
      name: http-management
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
